dist: trusty
sudo: required
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - libgtk2.0-dev
    - libgtksourceview2.0-dev
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-math-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - latex-xcolor
    - ghostscript
    - transfig
    - imagemagick
env:
  global:
  - NJOBS=1
  matrix:
  - COMPILER="4.02.3" TEST_TARGET="validate"      TW="travis_wait"
  - COMPILER="4.03.0" TEST_TARGET="validate"      TW="travis_wait"
  - COMPILER="4.04.0" TEST_TARGET="validate"      TW="travis_wait"
  - COMPILER="4.02.3" TEST_TARGET="test-suite"    TW=""
  - COMPILER="4.03.0" TEST_TARGET="test-suite"    TW=""
  - COMPILER="4.04.0" TEST_TARGET="test-suite"    TW=""
  - COMPILER="4.02.3" TEST_TARGET="contrib-hott"  TW=""
  - COMPILER="4.03.0" TEST_TARGET="contrib-hott"  TW=""
  - COMPILER="4.04.0" TEST_TARGET="contrib-hott"  TW=""
install:
- "[ -e .opam ] || opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config var root
- opam install -j ${NJOBS} -y camlp5 ocamlfind lablgtk-extras hevea
- opam list
script:
- ./configure -local -usecamlp5 -native-compiler yes -coqide opt -with-doc yes
- make -j ${NJOBS}
- ${TW} make -j ${NJOBS} ${TEST_TARGET}
